// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (title, user_id, content)
VALUES ($1, $2, $3)
`

type CreateTaskParams struct {
	Title   string `json:"title"`
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateTask(ctx context.Context, db DBTX, arg CreateTaskParams) error {
	_, err := db.Exec(ctx, createTask, arg.Title, arg.UserID, arg.Content)
	return err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, db DBTX, arg DeleteTaskParams) (int64, error) {
	result, err := db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, title, content, created_at, updated_at
FROM tasks
WHERE user_id = $1
ORDER BY id
`

type ListTasksByUserRow struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTasksByUser(ctx context.Context, db DBTX, userID int64) ([]ListTasksByUserRow, error) {
	rows, err := db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByUserRow
	for rows.Next() {
		var i ListTasksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET title = $1,
    content = $2,
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
`

type UpdateTaskParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, db DBTX, arg UpdateTaskParams) (int64, error) {
	result, err := db.Exec(ctx, updateTask,
		arg.Title,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
